query GetRecentVoteEvents {
    voteEvents(limit: 10, sort: [{ start_date: DESC }]) {
    id
    title
    start_date
    result
    agree_count
    disagree_count
    abstain_count
    novote_count
    organizations {
      id
      name
      type
    }
  }
}